import type { Metadata } from "next";
import { Goldman, Outfit } from "next/font/google";
import "./globals.css";

const geistSans = Goldman({
  variable: "--font-Prime",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Outfit({
  variable: "--font-Second",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Ahmed Kamal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} scroll-smooth`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
